### ISSUE TITLE
Run "in a new window" option should respect the default terminal app

### ISSUE THREAD

**Issue by reynoldsa** [microsoft/sudo#101]
### Sudo for Windows version

1.0.0

### Windows build number

26100.1.amd64fre.ge_release.240331-1435

### Steps to reproduce

1. Set `sudo` to run commands in a new window
2. Set default terminal to Windows terminal, instead of `conhost`
3. Run a command under `sudo`

### Expected Behavior

The new window to spawn using my selected default terminal.

### Actual Behavior

The new window is using `conhost` instead of WT.

**Comment by zadjii-msft** [comment]
Yea, this one's unfortunate. The OS can't hand off an elevated CLI application to a default terminal app. We're basically tracking that over in /dup https://github.com/microsoft/terminal/issues/10276. (see also https://github.com/microsoft/terminal/issues/10276#issuecomment-852215012).

Nothing `sudo` can do about that unfortunately. We just need to wait for the COM team to allow elevated processes to discover Packaged COM servers. 

Or you could `sudo wt -- {{the commandline you want}}`. That's contrived and subject to multiple re-interpretations of your commandline, but it'd probably work 😅
