### ISSUE TITLE
Can this be installed via winget?  If so, please add instructions  to README.md.

### ISSUE THREAD

**Issue by szalapski** [microsoft/sudo#111]
### Description of the new feature / enhancement

Can this be installed via winget?  If so, please add instructions to do so in README.md.

### Scenario when this would be used?

For anyone

**Comment by AvogatoWizardWhisker** [comment]
At this moment, there isn't a way to use winget to install sudo for Windows. I think this has been discussed in #57 , which is still in WIP. There hasn't been an update about sudo for a while as there's still some internal works #94

**Comment by joadoumie** [comment]
Thank you for the comment @szalapski -- we'll definitely add it into the README.md when it's ready. Also thank you for the response @AvogatoWizardWhisker -- this is correct. I will mark this as closed as we are tracking in the provided issues above and this issue is now ref'd there.
