### ISSUE TITLE
Command not found for powershell

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/sudo#113]
It's okay to call this command alone, but not with sudo.

![Image](https://github.com/user-attachments/assets/5809710e-0ee1-41d5-ba3b-f6396aba646b)

**Comment by joadoumie** [comment]
Thanks for providing the feedback!

I'm going to reference @lhecker's response to a similar bit of feedback below as this follows the same structure: 

```text
mkdir is a builtin command of PowerShell, not a standalone application like it would be on UNIX/Linux. You have to write sudo powershell -c '...' or sudo pwsh -c '...' to launch PowerShell and tell it to execute your command(s).

If you were to use cmd then sudo mkdir test would work. The builtin commands of cmd are quite a bit simpler and haven't changed in decades, so sudo supports them as a "shortcut" to help cmd users.
```

Generally, we are tracking improving these bits with #5 so I will ref this issue there!

**Comment by sunzhengbo** [comment]
Although it's possible, it's not perfect
