### ISSUE TITLE
why i can't use command  `sudo rm -rf "C:\"`

### ISSUE THREAD

**Issue by 8MiYile** [microsoft/sudo#28]
because not have rm command 
or i'm not update my windows?

（It's just a joke, the joke comes from the following picture）
![image](https://github.com/microsoft/sudo/assets/25455400/5bd45729-ab21-4dec-9de5-9f01c225a085)

**Comment by flobo09** [comment]
Because it's still not linux / unix ? . It's just an elevation command for windows.

**Comment by flobo09** [comment]
Because it's still not linux / unix ? . It's just an evelation command for windows.

**Comment by Ultra980** [comment]
> Because it's still not linux / unix ?

that's a bug with windows then

**Comment by shiroinekotfs** [comment]
lol

**Comment by shiroinekotfs** [comment]
> Because it's still not linux / unix ? . It's just an elevation command for windows.

Agree. The sudo command is just an elevation command, prompting for the highest privileges in Windows. 
 The `sudo` is just asking for UAC for further permissions, but does not replace the `rem` and `rd` commands in Windows.

**Comment by shiroinekotfs** [comment]
This `issue` should be closed, right? Because it seems to be the misunderstanding of the "new features" that the Microsoft team brings to Windows 11.

It also appears not to be an actual issue, nor a recommendation/enhancement.

**Comment by shiroinekotfs** [comment]
Oh, and, by the way, please don't run this command inside your work machine:

```cmd
sudo rm C:\ /s /q
```

I won't take any responsibility for your losing files in `C:\` after doing that.

**Comment by hez2010** [comment]
An elevated operation isn't necessary to be executed with the highest privilege.
On Windows you are still executing the command under the current user, except it's elevated. So you are only able to do what a normal admin user is permitted.  
The user that has highest privilege is TrustedInstaller, if you really want to do things like removing all files in the system directory, you would need to first switch the user to TrustedInstaller.

**Comment by shiroinekotfs** [comment]
> An elevated operation isn't necessary to be executed with the highest privilege. On Windows you are still executing the command under the current user, except it's elevated. So you are only able to do what a normal admin user is permitted. The user that has the highest privilege is TrustedInstaller, if you really want to do things like removing all files in the system directory, you would need to run the elevated command as TrustedInstaller.

Yeah true. Hope this `sudo` thing won't be implemented into Windows Server 2025 or Windows 11 Pro for Workstation (or higher privileges in Active Directory/Workspace/Workgroup). It only raises even more problems with security in Windows.

**Comment by Ultra980** [comment]
is anyone going to fix this

**Comment by shiroinekotfs** [comment]
> is anyone going to fix this

Fix *what*?

**Comment by Ultra980** [comment]
windows not being unix
