### ISSUE TITLE
Password via prompt to bypass UAC prompt..

### ISSUE THREAD

**Issue by mikeggh** [microsoft/sudo#44]
### Description of the new feature / enhancement

It would be nice to have the ability to type in a password of an administrator, or whatnot to bypass the UAC prompt.

### Scenario when this would be used?

Remotely, console pty, sshd, scriptable, etc..

**Comment by myronyuktaras** [comment]
*****Еволюція мозку серця душі*****

**Comment by myronyuktaras** [comment]
@DHowett

**Comment by myronyuktaras** [comment]
@mikeggh

**Comment by myronyuktaras** [comment]
@crutkas

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! This is actually already being tracked by another issue on our repo - please refer to #7 for more discussion.

/dup #7
