### ISSUE TITLE
use "audo" instead of "sudo"

### ISSUE THREAD

**Issue by LinuxStork** [microsoft/sudo#48]
### Description of the new feature / enhancement

It has come to my attention that Windows wants to add a "super user do," but Windows does not have a "super user." Instead, they have "administrator" user. Therefore, I propose they should use "audo" (administrator user do)

### Scenario when this would be used?

It's important because it paints false picture of windows as whole OS

**Comment by PH7N** [comment]
least troll-y linux user

**Comment by SkyyySi** [comment]
1. `sudo` stands for "substitute user do"
2. Linux also doesn't have a "super" user, there it is called "root"

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We're trying to consolidate naming discussion over in /dup #23. Feel free to continue the discussion there. Thanks!
