### ISSUE TITLE
Microsoft should not hijack the "sudo" name

### ISSUE THREAD

**Issue by pv2b** [microsoft/sudo#54]
### Description of the new feature / enhancement

Since there is already an open source project called "sudo", Microsoft should not hijack the same name for this tool. The code and usage is completely different, and having the same name will cause user confusion, including bug reports going to the wrong projects, and features not working as expected because of reading the wrong documentation.

Instead, I suggest that this project adopt a unique name. One suggestion would be "elev", as in "elevate".

### Scenario when this would be used?

Having multiple unrelated tools with the same name is a recipe for confusion, especially since there is another "sudo" that's included as part of WSL. Users may be confused that configuration of "sudo" within WSL is completely different from configuration of "sudo for Windows".

### Supporting information

When Microsoft introduced Powershell, it introduced a misfeature where the words "curl" and "wget" were aliased to "Invoke-Webrequest", something that has caused a lot of issues, including:

- Bug reports to the "curl" project relating to usage of the Invoke-Webrequest cmdlet
- Users having to type "curl.exe" to invoke the real "curl"

This issue was raised back in 2016, but at that point, removing that default alias was determined to be too late, because it might break earlier scripts. See this blog article: https://daniel.haxx.se/blog/2016/08/19/removing-the-powershell-curl-alias/

This is a similar case of something similar thjat happened in the past, and evidence of potential issues in the future if this is not addressed.

**Comment by zadjii-msft** [comment]
Thanks for the suggestion! We're trying to consolidate naming discussion over in /dup https://github.com/microsoft/sudo/discussions/23. Feel free to continue the discussion there. Thanks!

**Comment by pv2b** [comment]
> Thanks for the suggestion! We're trying to consolidate naming discussion over in /dup #23. Feel free to continue the discussion there. Thanks!

Why are you sending me into a discussion thread that has already been closed?

If you don't intend to change this, go ahead and say that instead of telling users to scream into the void. Thanks.
