### ISSUE TITLE
Remove case sensitivity in sudo commands

### ISSUE THREAD

**Issue by AvogatoWizardWhisker** [microsoft/sudo#60]
### Description of the new feature / enhancement

--[OPTIONS] should not be case sensitive. 

![image](https://github.com/microsoft/sudo/assets/89489853/6125ff89-79d1-4a0b-b57c-0ef408c6c4c9)

### Scenario when this would be used?

For example, the `-h` option prints help in lower-case, while `-V` and `-E` only work in upper-case. Usually, both of them should work, like how Windows commands do.

**Comment by joadoumie** [comment]
Thanks for the feedback! We'd like to keep this case sensitivity for compatibility with the sudo command. We know most Windows command-line tools are not case sensitive so we are breaking tradition here.
