### ISSUE TITLE
Unable to run PowerShell modules that requires administrator privileges with sudo

### ISSUE THREAD

**Issue by AvogatoWizardWhisker** [microsoft/sudo#62]
### Sudo for Windows version

0.1.5

### Windows build number

10.0.26063.1

### Steps to reproduce

I wanted to run PowerShell modules like `get-windowsupdate` with `sudo` since it requires to be run in an elevated PowerShell console.

![image](https://github.com/microsoft/sudo/assets/89489853/fb2a6f1e-cb2a-46a0-aba1-05cf29c35ff7)

### Expected Behavior

A UAC window will pop up and the command will run.

### Actual Behavior

After launching sudo, it showed `command not found`. 

![image](https://github.com/microsoft/sudo/assets/89489853/249a240f-4325-4df1-aa94-9bd85f4c7b62)

**Comment by andrewjwv** [comment]
I am having the same issue, I am simply running sudo directly after enabling it in directly in settings
For me I run sudo copy-item .\hosts .\hosts.old and get the same error of command not found

I've tried:
 Copy-Item (with capital letters)
with -source and -destination
with absolute paths

**Comment by gerardog** [comment]
For the time being, and until Microsoft publishes how sudo and PowerShell integration works, I recommend you elevate PowerShell commands using the following syntax:

`sudo pwsh { script }`

If you want to use variables, you need to use `sudo pwsh { Copy-item -source $args[0] -destination $args[1] } -args $src, $dst`

**Comment by andrewjwv** [comment]
Ye that worked except I typod when I said -source, its -path. It does work in that way for me. Hopefully op will test. Ill avoid until that is fixed tbh

**Comment by mominshaikhdevs** [comment]
the root issue is not powershell specific. rather, it is 
**"Implement a feature | syntax to indicate `sudo` that it should use the current shell(from which `sudo` is invoked) to execute the commands".**

this will solve both:

1. running shell specific commands without specifying the current shell name. 

For example: you will be able to run `cmd` specifc commands directly without prefixing `cmd`.

2. nested shell specific commands. 

For example: you could be running powershell specific commands inside nushell inside cmd and you won't have to prefix `pwsh`.
