### ISSUE TITLE
Add support for PowerShell commands/aliases

### ISSUE THREAD

**Issue by DanielCr2020** [microsoft/sudo#67]
### Description of the new feature / enhancement

Running `sudo Get-ChildItem`, for example, should run the command Get-ChildItem with elevated privileges, instead of failing with Command not found.
This could also work for aliases as well, such as `sudo del` --> `sudo Remove-Item` or `sudo kill` --> `sudo Stop-Process`

### Scenario when this would be used?

Wanting to quickly get to elevated privileges from a PowerShell window, instead of having to run the same command in command prompt. It would make it easier to run all commands with elevated privileges instead of having to use command prompt or the winget package.

**Comment by joadoumie** [comment]
Hey there! Thanks for the feedback - I agree. We are tracking the work we need to do to enable these exact types of experiences in another thread. This is great feedback!

/dup #5
